CREATE TABLE IF NOT EXISTS expenses_recurring (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    expense TEXT,
    frequency TEXT,
    dom INTEGER,
    bank_name TEXT,
    account INTEGER,
    amount FLOAT,
    category TEXT,
    renewal DATE,
    loan_mature_date DATE,
    notes TEXT
);

INSERT INTO expenses_recurring ('expense','frequency','dom','bank_name','account','amount','category','renewal','loan_mature_date','notes') VALUES
("Bartles", "30-Days", "0", "Sunmark", "5123", "150", "Utility", "3//8/2025", "", ""),
("AT&T", "Monthly", "14", "USAA", "810", "355.38", "Utility", "", "", ""),
("Bill Payment Transaction - DAVIS TRUCKING", "Monthly", "12", "Sunmark", "5123", "37.5", "Utility", "", "", ""),
("Blue Ox", "Monthly", "1", "USAA", "810", "450", "Utility", "", "", ""),
("Highlander Payment", "Monthly", "15", "Sunmark", "5123", "157.25", "Loan", "", "", ""),
("NYSEG", "Monthly", "25", "USAA", "810", "600", "Utility", "", "", ""),
("Progressive Insurance", "Monthly", "10", "Sunmark", "5123", "285.16", "Utility", "", "", ""),
("OneMain Consolidation Loan", "Monthly", "10", "DVA", "890", "718", "Loan", "", "46199", ""),
("Starlink", "Monthly", "16", "Sunmark", "5123", "120", "Utility", "", "", ""),
("USAA Loan Payment", "Monthly", "13", "USAA", "810", "550", "Loan", "", "46199", ""),
("American Express Credit Card", "Monthly", "18", "Sunmark", "5123", "60", "Credit Card", "", "", ""),
("LLBean Credit Card (Comenity)", "Monthly", "12", "USAA", "810", "175", "Credit Card", "", "", ""),
("TJX Rewards Credit Card", "Monthly", "12", "USAA", "810", "100", "Credit Card", "", "", ""),
("Comenity", "Monthly", "12", "USAA", "810", "29", "Credit Card", "", "", ""),
("Tractor Supply Credit Card (Comenity)", "Monthly", "12", "USAA", "810", "100", "Credit Card", "", "", ""),
("Apple - App Store Subscriptions", "Monthly", "11", "American Express", "2006", "21.58", "Subscription", "", "", ""),
("Calm", "Annual", "0", "American Express", "2006", "69.99", "Subscription", "45901", "", ""),
("Crunchyroll", "Monthly", "3", "USAA", "810", "7.99", "Subscription", "", "", ""),
("Github", "Annual", "0", "Sunmark", "5123", "108", "Subscription", "45992", "", ""),
("Microsoft Office 365", "Annual", "0", "USAA", "810", "107.99", "Subscription", "46082", "", ""),
("Netflix", "Monthly", "25", "Sunmark", "5123", "26.99", "Subscription", "", "", ""),
("Peacock TV", "Monthly", "1", "Sunmark", "5123", "13.99", "Subscription", "", "", ""),
("Rocket Money Premium", "Monthly", "19", "Sunmark", "5123", "7.56", "Subscription", "", "", ""),
("The Washington Post", "Annual", "0", "USAA", "810", "29", "Subscription", "", "", ""),
("Walmart+", "Monthly", "18", "USAA", "810", "13.99", "Subscription", "", "", ""),
("YouTube Premium", "Monthly", "4", "Sunmark", "5123", "22.99", "Subscription", "", "", ""),
("TSP Loan", "Monthly", "0", "None", "0", "0", "Loan", "", "46199", "Paid out of paycheck before I receive it"),
("Regal Cinema", "Monthly", "0", "", "0", "80", "Subscription", "", "", ""),
("ChatGPT", "Monthly", "10", "American Express", "2006", "22", "Subscription", "", "", "")